### ISSUE TITLE
AAID crashes once connection to car is successful 

### ISSUE THREAD

**Issue by samusishere** [hufman/AndroidAutoIdrive#323] opened 2021-06-15 20:32 UTC
Hello, 

I've noticed recently that with bmw connected functioning and registering as connected to the vehicle, the AAID app will only open momentarily and then it immediately force closes and after a few tries, actually causes my head unit to crash and reboot which sometimes allows for the connection to remain stable and other times it does not. 

Anyone else having this issue?

**Comment by donsaimon** [comment] 2021-06-16 19:04
Apart from the head unit crash, I have the same issue. See #322

**Comment by hufman** [comment] 2021-06-20 23:18
I haven't seen any new crashes come through the analytics, can you pull an `adb logcat` to see what specific crash you are seeing?

**Comment by unlive74** [comment] 2021-06-23 05:07
@hufman This morning with the MyBMW app connected: first AAID didn't start, after I started it on my phone it's crashed.
[logcat_06-23-2021_09-28-41.txt](https://github.com/hufman/AndroidAutoIdrive/files/6699048/logcat_06-23-2021_09-28-41.txt)

**Comment by unlive74** [comment] 2021-06-24 04:37
@hufman the application works well, but only until you launch it on your phone - look at 08:58:15

[logcat_06-24-2021_08-58-34.zip](https://github.com/hufman/AndroidAutoIdrive/files/6706282/logcat_06-24-2021_08-58-34.zip)

**Comment by hufman** [comment] 2021-06-24 05:51
I think I fixed this by unsubscribing from the MyBMW debug status announcements. The particular error message seems to indicate that the RPC buffer to receive these announcements was filling up, even though each individual message was tiny (900bytes combined to be bigger than 2MB), so I suspect there's some lag in some phones that cause the messages to back up and overflow, which I never could see on my own phone.
After about 30 minutes, check the latest build (c9fc6ff) and see if it helps.

**Comment by unlive74** [comment] 2021-06-24 06:16
@hufman New log: 11:11:43:637
[logcat_06-24-2021_11-11-54.zip](https://github.com/hufman/AndroidAutoIdrive/files/6706729/logcat_06-24-2021_11-11-54.zip)

**Comment by hufman** [comment] 2021-06-24 06:31
It's hard to tell, I'm not sure that the log says what version you installed, but it looks like you installed at 11:04 and the updated package only got [uploaded](https://github.com/hufman/AndroidAutoIdrive/runs/2901921189) at :03 after the hour. Can you confirm the version string of the installed app version?
If it is the new version, I guess the fix didn't help.

**Comment by unlive74** [comment] 2021-06-24 06:40
@hufman I run c9fc6ff: 

![photo_2021-06-17_16-46-18](https://user-images.githubusercontent.com/75434533/123214661-f306bd00-d4e0-11eb-97ce-957849afc4fe.jpg)

**Comment by hufman** [comment] 2021-06-25 00:44
I tried reducing how many copies of the BclListener are subscribed, maybe it helps? It was previously registering about 4 copies, now it should just register one, which should reduce how much traffic is passing through the Binder buffer.

**Comment by unlive74** [comment] 2021-06-25 04:37
I spent 20 minutes today doing everything to crash AAiD - I couldn't. :) The app works stably, I think the problem is solved.

**Comment by hufman** [comment] 2021-06-25 05:09
@unlive74 I'm glad to hear that!
@samusishere have you experienced this headunit crash recently? I pushed a tweak yesterday that might have helped.

**Comment by samusishere** [comment] 2021-06-25 05:26
@hufman I just saw the notification you pushed the new change! I noticed that using the mini app actually allowed the head unit to connect to my device and stay connected, and AAID wouldn't crash and neither would the headunit. It only occured whenever I used the BMW connected app. Still haven't been able to make the new MyBMW application connect to my vehicle and open the connection for apps.

**Comment by hufman** [comment] 2021-06-25 05:36
I'm glad you figured it out! I'm very intrigued by you saying the Mini app can connect, what sort of car do you have?

**Comment by samusishere** [comment] 2021-06-25 05:46
I have a 2013 late model year 528i with what AAID calls ID4++

**Comment by hufman** [comment] 2021-06-25 05:57
Haha it's true, both the MyBMW and the Mini apps (starting in version 1.4.0) include the USB Accessory configuration to load either brand! How funny is that! The Connected apps only have their own respective brands.
I'll close this then, it seems to be resolved.

**Closed by hufman** 2021-06-25 05:57 UTC

**Comment by unlive74** [comment] 2021-06-25 13:23
@hufman it seems to me that the latest builds are worse connected to the car. 3 days ago this worked almost always (may be 95%), but now only 50%. Connection occurs if you run AAID.

**Comment by hufman** [comment] 2021-06-25 14:25
I suspect something about the change in c9fc6ff, it directly relates to the connection listening, so I'll take a look.

**Comment by hufman** [comment] 2021-06-25 15:13
Just posted 3a63718 which might behave better, at least with my 1 test so far!
