### ISSUE TITLE
AAI app disconnection after few seconds

### ISSUE THREAD

**Issue by donsaimon** [hufman/AndroidAutoIdrive#322] opened 2021-06-15 12:38 UTC
Sometimes it happens that, after that AAI app has successfully connected, after few seconds it disconnects (Spotify icon disappears).
Nevertheless, in the car menu "device management" the APP voice is OK (the checkbox is correctly marked with the "V".
I have to uncheck Bluetooth box and check the app box again and after a certain time (it varies from few seconds to about 1 minute, it depends) AAI connects again. 
I have the last AAI version and BMW connected 4.1 app installed.

**Comment by hufman** [comment] 2021-06-16 20:46
Very interesting! I've seen that initial situation, where the app appears to connect, and then disconnects after a while (the Spotify icon never shows up in this case). The MyMini app disappears from the title bar after some 10 seconds, and then 30 seconds later it comes back and the app continues connecting as normal. I don't need to reconnect Bluetooth for this to continue working.
Will your Connected app reconnect after a minute, with no action on the Bluetooth connection? Does AAI reconnect if you kill it and open it again during this state?

**Comment by donsaimon** [comment] 2021-06-16 21:06
I have not tried what you ask.
This happened to me 3 or 4 times in the last days. 
Spotify icon appears and then disappears after a few seconds. Usually, when I am in car, I keep my phone in my pocket, so I never look at what happens to the apps (BMW and AAI) on my cell phone...

**Comment by TobifromGermany** [comment] 2021-06-19 06:00
Also bei mir ist auch das selbe Phänomen. Wenn ich in mein Auto einsteigen habe ich Bluetooth auf dem Handy schon aktiviert. Lege das Handy mit aktivierten Display und geöffneter AAID App in die Ablage. (Mir kommt es vor als würde die Verbindung so schneller aufgebaut, mit einem Handy im Standby nicht).
Es wird eine Verbindung aufgebaut, AAID App wechselt von grau nach grün, Spotify Symbol erscheint nicht im iDrive. Nach einem Augenblick wird die Verbindung wieder getrennt und neu aufgebaut. Diesmal erscheint Spotify und auch alle anderen Apps im iDrive. Danach gibt es keinerlei Probleme mehr.

**Comment by ahershey21** [comment] 2021-06-20 13:41
I have had the same issue. Things I have tried to resolve:
1. Turn bluetooth on and off - both on phone and on BMW.
2. Re-start Headunit (hold down power button for 20 seconds).
3. Update BMW Connection
4. Logoff and log back on to BMW connection.
5. Force stop AAI and restart.
6. Delete AAI, restart phone and reinstall - this is the most consistent in getting it to work again.

Hope this helps.

**Comment by donsaimon** [comment] 2021-06-20 15:44
Every time the issue appears you make all these things???

**Comment by TobifromGermany** [comment] 2021-06-20 15:56
Das wundert mich jetzt auch...
Die Verbindung kommt schon. Aber bricht eben beim ersten mal ab und baut sich nach kurzer Zeit wieder auf und läuft dann ohne Probleme. Insgesamt dauert dieser Vorgang nicht mal 1. Minute. Also eigentlich alles okay.

**Comment by hufman** [comment] 2021-06-20 17:48
@ahershey21 That extensive process shouldn't be needed, have you watched whether the Apps checkbox is connected or not? The Apps checkbox is entirely handled by BMWConnected/MyBMW, and uninstalling/reinstalling AAI won't have any effect. Restarting the phone might clear up memory to help the connection stay stable, but recent versions of MyBMW have been pretty reliable in that regard.

@donsaimon have you tried yet just waiting for a minute while the connection retries? That's usually all I need to do, and it seems that TobifromGermany has the same experience.

**Comment by donsaimon** [comment] 2021-06-20 17:51
I have waited some seconds, maybe not a minute... I will try.

**Comment by donsaimon** [comment] 2021-06-20 21:56
I have tried to wait 3 minutes... Nothing happens. App checkbox is OK....
The only way to have AAI app again is to open this app manually on the phone. As soon as I open the app, the connections starts again immediately. 
I have now created a Bixby (Samsung) routine that opens AAI app as soon as the phone is connected via Bluetooth to the car. Let's see if this helps.

**Comment by hufman** [comment] 2021-06-20 22:01
Very interesting! Can you tell me if you have Notification Access enabled? AAI only wakes up to run when the Bluetooth connection first starts up, and will shut down after the BMW app disconnects from the car. If Notification Access is enabled, AAI is still running in the background to notice the second time that the BMW app connects. Perhaps that is why I'm not seeing a problem. Can you confirm if you have enabled Notification Access?

**Comment by donsaimon** [comment] 2021-06-20 22:03
Yes, I have notifications access enabled.

**Comment by donsaimon** [comment] 2021-06-21 11:19
Walter, shall I disable notifications access?

**Comment by ahershey21** [comment] 2021-06-21 14:35
I don't do the list every time, but the list is the things I have tried. One thing I have noted is that this is fairly infrequent and is usually after it was working, then I ran into a shop for a quick errand, then came out and it wouldn't work. Based on one of your earlier comments, I wonder if it is not releasing the bluetooth connection.

There are only 2 things that have semi-consistently worked. 

1. uninstall and reinstall the app. I have tried closing the app, forcing it to stop and restarting - but this didn't work. 
2. Wait until my next drive and the car has sat for awhile.

**Comment by hufman** [comment] 2021-06-21 16:09
@donsaimon disabling notification access shouldn't be needed, I mentioned it because notification access provides another way for the app to start up the connection and should only help. Of course, it's easy enough to disable access and test.

@ahershey21 that's very curious! AAI itself doesn't have a Bluetooth connection and shouldn't have anything to release, and instead is just talking TCP to the MyBMW app. Force Closing should be just as effective as Clearing Storage or Uninstalling, so that's also an unexpected observation. Keep in mind that AAI is not the app that is connecting to the car, MyBMW is responsible for the actual connection: Please note whether the Apps checkbox is checked in the car, indicating a successful connection from MyBMW, which AAI can't improve much. Manipulating AAI will only indirectly improve the connection success by triggering external Android behavior which might trigger MyBMW to behave differently.

**Comment by donsaimon** [comment] 2021-06-21 16:16
Ok thanks. I have disabled notifications access. Let's see if it helps

**Comment by ahershey21** [comment] 2021-06-22 14:38
Had only 1 minor trouble yesterday, but when I logged back into MyBMW, this seemed to fix the App connection. I then had to re-start AAI and all worked.

**Comment by hufman** [comment] 2021-06-22 15:55
Indeed, the MyBMW app logging out is the main problem I experience lately: I sent them an in-app feedback to complain about it and bring back the long-lived login session from the Connected app.

**Comment by ahershey21** [comment] 2021-06-22 19:12
This could be the primary issue. With MyBMW, I find that about once a week it logs me out and I have to log back in.

**Comment by hufman** [comment] 2021-06-24 06:12
If you watch the BCL Tunnel Performance (after enabling Advanced Settings, visible either in Connection or Car Information), you might catch it in a weird state: You'll see the Connection Lifetime bouncing up and down, and the Unacked Bytes will bounce between positive and negative. It seems that sometimes the BMW app starts up two BCL Worker Threads, and the connection is not usable until 30 seconds later when the watchdog kills the connection and restarts it. This is the symptom I experience, is this what you see?

**Comment by unlive74** [comment] 2021-06-26 11:36
@hufman  3a63718 works perfectly, 2f1afdb never connected automatically, I checked it 8 times, every time I had to run the app.

**Comment by donsaimon** [comment] 2021-06-26 12:55
I use c87b487, no connection issues at all!

**Comment by hufman** [comment] 2021-06-26 15:52
Excellent, glad to hear!
I think this issue (BMW disconnects briefly on some startsup and AAI doesn't try to reconnect) can be closed then! BMW is still disconnecting and reconnecting by itself, not much to be done there, but AAI should now be reconnecting properly.

**Closed by hufman** 2021-06-26 15:52 UTC

**Comment by unlive74** [comment] 2021-06-26 18:17
@hufman 3a63718 is earlier build than 2f1afdb. By the way, 1bdd007 has the same problem - it connects in 30% of cases, you have to run the app. 3a63718 connects more stably.

**Comment by hufman** [comment] 2021-06-26 23:22
I'm interested to hear if c65108e works better, I feel more confident about that change.

**Comment by unlive74** [comment] 2021-06-27 13:00
Everything is bad :) watch from 11:53

[logcat_06-27-2021_11-56-58.zip](https://github.com/hufman/AndroidAutoIdrive/files/6721609/logcat_06-27-2021_11-56-58.zip)

**Comment by hufman** [comment] 2021-06-27 17:26
I think the log shows the change was effective (CarCapabilities was restarted in the same MainService instance), but the BMW app sent ACCESSORY_DETACHED both times. If you watch the BCL Tunnel Stats, did it show the behavior of two tunnels running simultaneously?

**Comment by unlive74** [comment] 2021-06-28 05:10
@hufman Ugf! This morning I tried to repeat yesterday's problem with c65108e. Before that, I did a "clean" installation of AAiD - perhaps this influenced the situation, or perhaps the fact that when recording the screen AAiD was running all the time on my phone ... I will test it again. :)
ps: Spotify always turns on when Num Connections: 10 - (at least) (or it doesn't turn on if Num Connections: 10 and it hasn't turned on yet).

**Comment by unlive74** [comment] 2021-06-28 10:04
I've done it! I might be a jerk, but I'm pretty sure running the app stimulates the connection. I started my car, probably at 12:50 (or 12:51)

[logcat_06-28-2021_12-54-03.zip](https://github.com/hufman/AndroidAutoIdrive/files/6725266/logcat_06-28-2021_12-54-03.zip)

https://user-images.githubusercontent.com/75434533/123618420-9f1e1000-d821-11eb-8421-95c1537900a8.mp4

**Comment by ahershey21** [comment] 2021-06-28 12:35
For me, so far so good with c87b487, I have not tried to update with a later version yet. 

I have found that I sometimes will have a delay of 10-20 seconds after starting the car for it to kick in, but when it does, it remains stable. 

I do tend to think it is the BMW app that is missing the connection problem, not AAI. Interestingly on my S21 Ultra, the My BMW isn't listed as a option to never sleep, so I wonder if it may be that the BMW Connection has a bug that puts it in an inconsistent state. 

I'll update to the nightly build and try to see if I can re-create the problem (so far with c87b487 I have not been able to recreate, so it may be fixed).

**Comment by donsaimon** [comment] 2021-06-28 12:40
I can confirm that c87b487 is very stable, no issues for the moment, so I keep it and I do not update to following versions.
I use BMW Connected 4.1

**Comment by hufman** [comment] 2021-06-28 16:42
@unlive74 from looking at the logs, here are the important bits:
```
[06-28 12:50:24.076 24486:24486 I/A2DPBroadcast]
Notified of A2DP status: BMW 37069 connecting -> connected
[06-28 12:50:25.398 24486:24486 I/A2DPBroadcast]
Notified of A2DP status: BMW 37069 connected -> disconnected
[06-28 12:50:30.919 24486:8518 I/CarProber]
Found open socket at 4007, detecting car brand
[06-28 12:50:32.014 24486:24486 D/MainService]
Starting CarCapabilities thread
[06-28 12:50:32.022 24486:9708 I/MainService]
Starting to discover car capabilities
[06-28 12:50:32.034 24486:9709 I/MainService]
Starting notifications app
[06-28 12:50:33.455 24486:24486 I/IDriveConnectionListen]
Received car announcement: com.bmwgroup.connected.accessory.ACTION_CAR_ACCESSORY_ATTACHED bmw
 14@127.0.0.1:4007
[06-28 12:50:33.520 24486:24486 I/MainService]
Starting up service me.hufman.androidautoidrive.MainService@c06df95
[06-28 12:50:33.681 24486:24486 I/A2DPBroadcast]
Notified of A2DP status: BMW 37069 connecting -> connected
[06-28 12:51:04.989 24486:24486 I/IDriveConnectionListen]
Received car announcement: com.bmwgroup.connected.accessory.ACTION_CAR_ACCESSORY_DETACHED
[06-28 12:51:05.056 24486:9708 I/CarThread]
Shutting down thread Capabilities due to RuntimeException: org.apache.etch.util.TimeoutException: timeout waiting for de.bmw.idrive.BMWRemoting._result_sas_certificate(-1671204168)
[06-28 12:51:05.056 24486:8518 W/CarProber]
Exception while probing car
[06-28 12:51:05.060 24486:9709 I/CarThread]
Shutting down thread Notifications due to RuntimeException: org.apache.etch.util.TimeoutException: timeout waiting for de.bmw.idrive.BMWRemoting._result_sas_certificate(-1671204168)
[06-28 12:51:06.052 24486:24486 I/CarConnectionListener]
Received car status announcement: com.bmwgroup.connected.accessory.ACTION_CAR_ACCESSORY_DETACHED
[06-28 12:51:09.176 24486:8518 W/MessageQueue]	# car prober has shut down, meaning MainService destroyed
Handler (android.os.Handler) {c521bad} sending message to a Handler on a dead thread
java.lang.IllegalStateException: Handler (android.os.Handler) {c521bad} sending message to a Handler on a dead thread

[06-28 12:53:11.100 24486:24486 I/BluetoothDevice]
fetchUuidsWithSdp() for device F83002 called by pid: 24486 tid: 24486
[06-28 12:53:11.110 24486:24486 I/MainService]
Starting up service me.hufman.androidautoidrive.MainService@bfc3094
[06-28 12:53:23.461 24486:24486 I/IDriveConnectionListen]
Received car announcement: com.bmwgroup.connected.accessory.ACTION_CAR_ACCESSORY_ATTACHED bmw 14@127.0.0.1:4007
```

You can see the A2DPListener noticing the car connect, disconnect, and connect again, and the IDriveConnectionListen tag noticing whenever the official BMW app connects and disconnects. What I think is happening is that, when the car DETACHES at 12:51:04/12:51:06, I think the MainService is shut down (note that the MessageQueue fails to reschedule the CarProber at 12:51:09, which means CarProber has been shut down as part of MainService shutting down at some point). When you start the app, it creates a new MainService instance at 12:53:11. I think because MainService has shown a notification and then hidden it, your phone shuts down the service and then it stops doing the repeated UUID scanning trick to trigger MyBMW into connecting. As soon as you start up the UI, it sends a UUID request at 12:53:11 and then the normal connection process starts up again.
I wonder if MyBMW is experiencing the same service shutdown: Their code is meant to retry every 20 seconds or so, but perhaps because it has also shown a notification and then hidden it when the Bluetooth disconnected briefly, they are stopped from trying again.
I'll ponder and see if there's a way I can improve this somehow.

Anyways, as a workaround, you should be able to toggle Bluetooth Music through the car dashboard and get the connection working again while you are driving around.

**Comment by unlive74** [comment] 2021-06-28 18:00
@hufman for example 3a63718 works very stable without the trick of running aaid on my phone.  what has happened since then?

**Comment by hufman** [comment] 2021-06-28 19:15
[Here are the changes](https://github.com/hufman/AndroidAutoIdrive/compare/3a63...c65108) between those commits. The one thing that looks relevant to me is 2f1afdb, which waits 5 seconds before trying to trigger the UUID trick (which unsuccessfully hoped to avoid the double-BCL problem) and also only triggers the UUID if A2DP is connected. I wonder if that later piece is causing trouble, but I'll just revert the entire commit.

**Comment by unlive74** [comment] 2021-06-29 05:54
Tested 3a5feb7 today. There was no stable connection.

log: 
[logcat_06-29-2021_09-45-00.zip](https://github.com/hufman/AndroidAutoIdrive/files/6730971/logcat_06-29-2021_09-45-00.zip)

Смотреть начиная с 09:41:13:739.

**Comment by hufman** [comment] 2021-06-30 02:45
Thank you for the logs and for always pointing out the timeframe of your connection, that has been very helpful.
I'm glad to be working towards a more reliable connection with you and it's almost done.
I did experience a stuck connection today similar to what you showed in logcat_06-29-2021, and so I have some more changes for you to test:

The mainservice_nostop branch ([run](https://github.com/hufman/AndroidAutoIdrive/runs/2948305839) [apk](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/androidautoidrive-latest-mainservice_nostop-nomap-sentry-release.apk)) changes an event listener to no longer stop the MainService when the BMW app tells it the car has disconnected. I think this might have been causing some of the weird log entries, where the service doesn't seem to notice the subsequent connections.
The mainservice_notification branch ([run](https://github.com/hufman/AndroidAutoIdrive/runs/2948306494) [apk](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/androidautoidrive-latest-mainservice_notification-nomap-sentry-release.apk)) includes the mainservice_nostop change and also changes the connection notification to always show, even while MainService is just waiting for a connection. I think this is technically more correct for the Android System to not kill the process in the background, and is a useful indicator for the user to show the waiting status.

I'd be interested to hear your testing results. I suspect the `mainservice_nostop` might be enough, but the status indication of `mainservice_notification` might be desirable too.

**Comment by unlive74** [comment] 2021-06-30 04:33
No problem - I'm always happy to be a guinea pig! Start at 09:03

[logcat_06-30-2021_09-04-49.zip](https://github.com/hufman/AndroidAutoIdrive/files/6738028/logcat_06-30-2021_09-04-49.zip)

**Comment by hufman** [comment] 2021-06-30 14:30
Which branch are these logs from?

**Comment by unlive74** [comment] 2021-06-30 14:36
1.3rc2-30-ec49e1c-mainservice_notification 30 июн. 2021 г. 7:35:25

**Comment by unlive74** [comment] 2021-06-30 14:44
1.3rc2-30-ec49e1c-mainservice_notification 30 июн. 2021 г. 7:35:25

**Comment by hufman** [comment] 2021-06-30 14:58
Excellent, it shows that the same MainService@2a5f490 instance is being used the entire time!
I suppose the next thing would be to figure out why the BMW code is starting two BCL workers...

**Comment by hufman** [comment] 2021-07-01 06:19
I've confirmed that the two BCL workers is indeed a bug in the BMW app when handling the car's brief disconnecting during the initial connection process, and AAI is not triggering it! So I merged the notification branch to master, which should make it at least reliably automatically reconnect after the BMW app times out and restarts the connection after 30 seconds.

**Comment by ahershey21** [comment] 2021-07-10 12:28
I have not had the problem anytime in the last week. It seems to be fixed.

**Comment by donsaimon** [comment] 2021-07-10 12:31
I am still using the "old" c87b487 and it is good, no issues at all...
I am afraid to update... It is a good version...

**Comment by ahershey21** [comment] 2021-07-10 12:51
I try to regularly upgrade to the nightly builds (about once a week). The version I have been using is bf2c39b and it seems to be stable and works.
