### ISSUE TITLE
App closes whole connection to the car

### ISSUE THREAD

**Issue by muenze96** [hufman/AndroidAutoIdrive#252] opened 2021-04-18 10:17 UTC
I had to drive for longer distances this weekend, and after about 45 minutes the app closes and the music turned off, without doing anything. I have installed the newest nightlies.

**Comment by bogdan-calapod** [comment] 2021-04-18 17:38
Does the `Apps` connection remain open ? Also, what BMW app are you using ? (`Connected` or the new `MyBMW`)

There has been some talk on #149 about `MyBMW` having poor stability with keeping the Apps connection up.

**Comment by hufman** [comment] 2021-04-18 19:20
Yes, check the car's Bluetooth settings to confirm whether the Apps checkbox stays checked. BMWConnected/MyBMW manage this tunnel, and if they close the tunnel for any reason, AAI will be disconnected and the music will stop.
Without pulling out the phone, you can disconnect the Bluetooth Music in the car and reconnect it, and the apps tunnel should start back up and the music will resume.

**Comment by hufman** [comment] 2021-04-19 19:31
I'm going to close this as a duplicate of #244

**Closed by hufman** 2021-04-19 19:31 UTC
