### ISSUE TITLE
Car connection problem (connect without apps) after switching to My BMW

### ISSUE THREAD

**Issue by unlive74** [hufman/AndroidAutoIdrive#244] opened 2021-04-07 03:58 UTC
By the way, it seems to me that now the connection with my car (X2, EntryEvo ID5, your app recognizes it as BMW ID6L) is more often without applications (only the phone and bluetooth audio). Previous version + Connected 6.4 = 90% success, Current version + My BMW = 50/50. When reconnecting, it's usually corrected.

**Comment by hufman** [comment] 2021-04-07 16:35
MyBMW is a little trickier to quickly identify the connection status, since MyBMW doesn't add apps to the car itself. However, one clue is that the car's Bluetooth Apps checkbox will be checked. Can you confirm whether the Apps checkbox is checked? If this isn't checked, then MyBMW didn't successfully connect and the Bluetooth connection will need to be restarted.

Additionally, AAI will show some connection status in the phone interface, a single-line summary on the main page and the full connection details in the Connection tab (accessible through Advanced Settings or by tapping the connection icons in the sidebar). Can you show what status you are seeing?

**Comment by unlive74** [comment] 2021-04-07 16:52
Of course, as always, the "Applications" checkbox is checked. Almost every new start of the car this checkbox is empty and you will have to reconnect bluetooth and then it's checked again. The connection tab is missing if I use My BMW (I try yesterday's AAI build). Tomorrow morning (for you it'll be tonight) I'll shoot a video. It seems to me this is a story about timeouts - something doesn't have time ...

**Comment by hufman** [comment] 2021-04-07 17:35
Thank you for the quick response! I look forward to the video showing what you see :)

The Connection tab is hidden by default, unless you enable Advanced Settings in the Settings tab. Tapping the connection icons in the header of the sidebar will also bring you to the Connection tab. It does not rely on any other installed software to show or hide itself.
If the car's Apps checkbox isn't being checked, then MyBMW isn't successfully connecting to the car, which is needed before the apps can show up in the car. I received a logcat log from someone yesterday who also indicated that MyBMW was failing to connect the first time, and that log seemed to show that the MyBMW BtService was crashing. It was juxtaposed near other log messages saying that MyBMW was denied permission to scan for Bluetooth devices due to not having Location permissions, and I wonder if this might be the reason for the crash. Do you have Location permissions granted to MyBMW?

It is still early for the MyBMW app, and they are still working bugs out. They have Firebase Crashlytics enabled, and so each of those crashes is reported back to them for debugging. Until the June deadline, using BMW Connected is totally valid, and perhaps preferred since it still provides some extra functionality!

**Comment by unlive74** [comment] 2021-04-08 11:51
I don’t understand anything. There are no apps today. What am I doing wrong? [https://photos.app.goo.gl/C36jWQQLTqQ7dRx46](url)

**Comment by DominikS66** [comment] 2021-04-09 06:26
@hufman I've also noticed that the MyBMW App seems to have problems sometimes which results in missing apps functionality in iDrive 6. Simply switching BT connection in iDrive 6 solves the problem in most cases (quite more than 50/50). Checking MyBMW apps permissions ifound that the access to locations is only granted during app is active and used. There#s no option for "always accepted" as I've seen in BMW connected app. I'll try following workaround on my Samsung S9: Switching off "battery optimization" for MyBMW app (so the standby MyBMW app won't be killed externaly)
BTW, what I've also seen on my Smartphone is that on first BT connection after starting iDrive the MyBMW BT connection is broken after some seconds and then re-established again. This happens nearly on every BT connection.

**Comment by DominikS66** [comment] 2021-04-09 07:33
@unlive74 please try to control the Spotify app from AAID. If this doesn't work correct, kill Spotify app within Android Apps Settings. This worked for me in such a situation.

**Comment by hufman** [comment] 2021-04-09 08:34
Thank you for the video showing what you are experiencing! However, since the car isn't adding the checkmark to the Apps box, this indicates a problem with MyBMW itself talking to the car, and AAI can't do anything to help :( Are you running the latest version of MyBMW? I believe version 1.3.2 (March 30th) and 1.3.3 (April 6th) are tested to work successfully. I'd expect the Play store to upgrade this automatically, but please check.
Otherwise, BMW Connected 6.4 is still completely valid and provides more in-car functionality. If you don't need remote functionality (and so don't need to log in to ConnectedDrive), you won't even miss the service when it shuts down in June!

**Comment by unlive74** [comment] 2021-04-10 05:14
> @unlive74 please try to control the Spotify app from AAID. If this doesn't work correct, kill Spotify app within Android Apps Settings. This worked for me in such a situation.

@DominikS66 Thanks for the solution, It seems it solved the problem. Everything works so far, but I'll watch for a few more days.

@hufman I'm running MyBMW ver. 1.3.3 (April 6th). BMW Connected 6.4 really works great, but you always want something new! :)

**Comment by unlive74** [comment] 2021-04-14 06:27
> For the purpose of this issue, AAI now supports the North American version of MyBMW and starts up automatically when the phone connects to the car. The issue #244 would be the better place to track any MyBMW connection instability.

@hufman Does the North American version and the European version differ in terms of bt connectivity?

**Comment by hufman** [comment] 2021-04-14 15:05
I don't believe they intentionally differ, though I feel that the European MyBMW 1.3.2 on my Pixel2 connected more reliably than the American MyBMW 1.3.3 on my Galaxy S9, not sure what factors are causing it. AAI had to be updated for the different location of the security module in America :)

**Comment by fabssor** [comment] 2021-04-20 16:49
I tested it today with the version 1.3.4 of the My BMW App. Connection still works but is more unreliable for me. First connection never works. I have to go to the IDrive Settings disconnect and then reconnect to get the App checkmark in the IDrive Settings. Still this seems to be a My BMW problem...

**Comment by kvphani** [comment] 2021-04-28 08:37
I have the same problem, where the first connection works  and second connections never work unless I disconnect the device and reconnect. But, instead I tried to force stop My BMW app and then open both My BMW and AAI for the second connection (using tasker) and it works. So, problem could be My BMW app.

**Comment by DominikS66** [comment] 2021-04-29 12:12
I've tested my own build 1.2.2-779e745 checked out from master on Monday. I wanted to test commit https://github.com/hufman/AndroidAutoIdrive/commit/9783bb27e6fad93474e5129a4107a2a602c466d7 and newer commits. Tested with MyBMW App 1.3.4. Now I see another problem: After 30 Minutes, MyBMW stops apps support. On older versions of AAID, toggling bluetooth audio connection in ID6 bluetooh profile for my Samsung S9 brought apps back to ID6. This workaround doesn't work anymore. Instead, I've got a timeout reported via sentry when I toggled bluetooh completly in ID6:
![grafik](https://user-images.githubusercontent.com/81849700/116548708-edcc2e00-a8f4-11eb-8e38-f81611bdabca.png)

**Comment by hufman** [comment] 2021-04-29 15:35
That's so cool, I'm happy you figured out the Sentry integration!
In this case, [CarProber](https://github.com/hufman/AndroidAutoIdrive/blob/master/app/src/main/java/me/hufman/androidautoidrive/CarProber.kt) is probably just showing a symptom of the tunnel being down. It runs in two modes (check for new, and watchdog the current), and the mode that crashed is trying to start up a new connection to the car. Specifically, it has noticed that the Etch RPC proxy port is open (in probePort), but it failed when trying to establish the full Etch RPC connection to it (in probeCar). So, this stacktrace is detecting that the MyBMW app is running and has started the proxy port, but isn't accepting traffic to it.
The TimeoutException is fully caught and reported manually, and then CarProber continues to watch the tunnel port to see if it will open up. Did your Sentry catch lots of repeated events? I thought it to be a transient error while the tunnel is coming up or down, but if you are seeing them repeat every few seconds, then the tunnel is stuck very hard.
Having your own Sentry is helpful, you get a clearer stream of information specific to your testing :)

**Comment by DominikS66** [comment] 2021-04-30 07:25
Good morning @hufman , No I didn't see repeated events. Normal behavior
I've made some more tests with my version and I think I've found a reproducible failure. Details on the test:
Apps:
MyBMW 1.3.4
AAID 1.2.2-425-779e745 (my own build with gmaps and sentry)
Spotify 8.6.20.1063
2019 BMW F20 ID6L NBT entrynav2
Test issue:
Preps: Start iDrive, wait for apps connection in ID6, start Spotify playing music from a playlist
Test: goto Bluetooth settings, Connection setting for connected Smartphone (my Samsung S9), disable Bluetooth audio. Result: Playing music stops, Apps disappeared (as expected)
Enable Bluetooth audio again, then I expected apps to return and Spotify go on playing...failed.
What I've mentioned:
- in AAID there's an information like "Waiting for apps connection to be started" and after some secondes "try toggling bluetooth audio" but nothing happens.
- sometimes the Apps square in ID6 appears for about 30 seconds, but there are no Apps. Square disappears again.
This is the same behavior that I've mentioned on the MyBMW "30-Minutes disconnection". Most time I play music from Spotify when driving my ca.

Same test with AAID 1.2.2-413-ddd2098 works as expected. Apps functionality comes back after enabling bluetooh audio. From my side this version seems to be most stable version - but with this version I also mentioned the Spotify control issue described in issue #254 .

**Comment by DominikS66** [comment] 2021-05-03 09:44
Information upate: Testing arround with different commits I've found out that the problem described in my previous post appears with version 416, commit https://github.com/hufman/AndroidAutoIdrive/commit/1e447db17673b62f84629c085042bcbd2aab6715 
I've build a personal "dirty" version with latest commits https://github.com/hufman/AndroidAutoIdrive/commit/82f316eef54c534338b272906776d105bcbd3032  (version 1.2.2-436) an replaced (rolled back) source code of file app/src/main/java/me/hufman/androidautoidrive/connections/BtStatus.kt to previous commit https://github.com/hufman/AndroidAutoIdrive/commit/51e2e317c65520128fc618b13f937419502258e5. This self-made version brought back more reliable bt connection and also the "restart" workaround by disabling/enabling bt audio in ID6 works again.

**Comment by hufman** [comment] 2021-05-03 14:55
Oh very interesting, thank you so much for figuring that out! I thought that code wasn't doing anything except raising errors, do you see the BLUETOOTH_ADMIN errors in your build now too?
But now that I think about it, the errors were only for registering the UUID listener. Are you able to fix the problem if you only add `device.fetchUuidsWithSdp()` back in, perhaps in the A2DP listener?

**Comment by DominikS66** [comment] 2021-05-03 18:02
@hufman Inow I checked the logs via netwrok remote adb. I didn't see this BLUETOOTH_ADMIN error in my logs. Everything looks well around btStatus module.

**Comment by hufman** [comment] 2021-05-05 15:46
Did you have any luck with adding `device.fetchUuidsWithSdp()`? I'd welcome a Pull Request with this fix if it helped you :)

**Comment by DominikS66** [comment] 2021-05-06 17:13
Hello @hufman yes adding one line `device.fetchUuidsWithSdp()` in `bluetoothListener` object definition solved the problem. But: I've checked the BLUETOOTH_ADMIN error again and found that the permission `android.permission.BLUETOOTH_ADMIN` is missing in AndroidManifest is missing. I've made also a version with the old code of btstatus.kt and additional permission `android.permission.BLUETOOTH_ADMIN`
Both versions seem to work and the BLUETOOTH_ADMIN error dissappeared. I'll test more in the evening. Do you think it's better to leave the code for uuid out ? What's been the reason for this code ?

**Comment by hufman** [comment] 2021-05-06 21:01
Thank you so much for investigating!
The `device.fetchUuidsWithSdp()` function is used to refresh the phone's knowledge of what endpoints are available in the car. Later in the code, the code examines `device.uuids`, which is the cached results of that endpoint search. The Bluetooth SPP UUID (serial port profile) will be in this list of endpoints if the car supports Apps over Bluetooth. My guess is that MyBMW isn't conducting this `fetchUuidsWithSdp` step on its own, and the phone sometimes doesn't fetch it automatically, and so MyBMW then doesn't see the SPP UUID to try to start up the Apps connection.

AAI itself doesn't do anything with the `device.uuids` list except to show that checkbox about "Bluetooth Apps are Supported". However, I think the act of fetching the uuids sends the UUID information over to MyBMW to trigger the connection.

I much prefer the smaller change of adding the single-line `fetchUuidsWithSdp` as opposed to adding the BLUETOOTH_ADMIN permission. The UUID Listener code that requires this permission doesn't actually do anything except log what it found. I don't want to add extra permissions to the app if they aren't needed :)

**Comment by DominikS66** [comment] 2021-05-07 19:20
@hufman as I'm new to Github, how to commit a change I've made in my local master branch to a pull request ? Therefore, it seems I need a new branch first ? (Can someone give a little help ?)

**Comment by hufman** [comment] 2021-05-07 20:28
Gladly! Welcome to the exciting world of Git and Open Source! Github only adds the extra Pull Request step at the end, but it's super fun!
So the first concept is that each Git repository is a full-fledged independent repository. https://github.com/hufman/AndroidAutoIdrive is a repository, all of the forks on Github are each their own repository, and the local clone you have on your computer is its own repository. Each of these repositories has its own master branch, and can have any other branches. They start out the same (as a clone) but commits can be added to the master or any other branch on the local repository.
To synchronize changes between these various repositories, you've probably used `git pull` to download commits from one repo to your own, typically commits on the master branch. This will run into issues if your master branch has extra commits, and so one of the most important rules is that new features should be on separate branches and not on master. This allows you to keep pulling new changes on the master branch while the feature branch is being developed or discussed in a Pull Request.
Similarly to pulling, you can push commits to another repository. I can push directly to hufman/AndroidAutoIdrive, and you would have permission to push to your own DominikS66/AndroidAutoIdrive after you click the fork button at the top of the page. After you make a commit on your local computer, you can push the branch with that commit up to the DominikS66/AndroidAutoIdrive repository and then open a Pull Request to request that I pull that branch to merge into my repository.

That's the theory, here's the actual commands:

1. Click the fork button at the top to create a new repository in Github that has all of the commits of hufman/AndroidAutoIdrive. It should be located at https://github.com/DominikS66/AndroidAutoIdrive
2. In your local computer's Git repository, add this fork as a named remote destination to push code to: `git remote add fork git@github.com:DominikS66/AndroidAutoIdrive.git`. This will add this destination to the list in `git remote -v`  (in Github docs, you'll see my source repo called `upstream` and your fork would be called `origin`, just fyi)
3. Make a new branch, starting at your current master branch: `git branch feature_fetchUuidsWithSdp && git checkout feature_fetchUuidsWithSdp`  (a shortcut for these two commands is `git checkout -b feature_fetchUuidsWithSdp`)
4. The `git status` command should now say that you are `On branch feature_fetchUuidsWithSdp`
5. Commit any changes with the `git add; git commit` commands like normal
6. Next, push this branch to your Github repo: `git push fork feature_fetchUuidsWithSdp`
7. If you refresh mine or your AndroidAutoIdrive page in Github, it will show a banner (for about 15 minutes) about creating a Pull Request for this recently-pushed branch, or you can go to the branches list page and create from there: https://github.com/DominikS66/AndroidAutoIdrive/branches
8. After you finalize and create the Pull Request, I'll get an email to review it, and probably merge it into my repository for everyone else to enjoy.

In case you had made commits to your local master branch, these will still be in the branch above, and then you can reset the master branch to match my master branch and be ready to pull future commits:
1. `git checkout master && git reset --hard origin/master`
2. `git pull origin master`
3. `git push fork master`

This is just a summary, the [full Github docs](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests) are helpful too.

Give it a try! Reach out over Gitter or any other methods with any questions!

**Comment by hufman** [comment] 2021-05-12 07:45
I was able to catch some logs of this connection breaking (after playing 2.5 hours of music!) and thought I might share what I'm learning.
At least in this single case that I logged, as opposed to MyBMW closing, it seems that actually the Bluetooth connection itself disconnected: I'm seeing logcat messages about the A2DP device disconnecting, and then the tunnel watchdog shuts down, and then MyBMW announces the disconnection to the other processes on the phone. The A2DP tries to start back up 10 seconds later, disconnects 2 seconds later, and starts back up again 2 seconds later. At this point, I see MyBMW notice the connection and start the connection process again. In this instance, the A2DP disconnects again, right before the apps tunnel finishes starting, and then my log doesn't include anymore information.

I spent some time comparing the MyBMW logging messages to its code, to trace how the logic flows through it, and I discovered something: The BLUETOOTH_UUID message that AndroidAutoIdrive doesn't need, and so I removed it but then @DominikS66 found it was helpful in reconnecting MyBMW after disconnecting? I was able to confirm that this BLUETOOTH_UUID message is the entrypoint that starts up the entire Bluetooth Apps connection process inside MyBMW.

MyBMW does do this UUID refresh, but only when the low-level Bluetooth connection first connects, not after toggling Music, and so the connection logic could possibly get stuck in certain situations. I put back the additional UUID refresh code from my A2DP connection handler, and together with DominikS66's testing and pull request, this should help the connection handling.

However, this issue was opened on April 6th, while the change that removed UUID refreshing was pushed on April 19th, so something else might still be happening.

**Comment by berseker** [comment] 2021-05-12 20:03
great job, I really look forward to the next developments of this great app :D I confirm that the connection today went smootly without any issue during the daily commute from work

if I can be more useful to send logs or in any further way, please feel free to contact me, I would love to try what I can do to support

**Comment by dimakaob** [comment] 2021-05-13 08:18
Maybe it's already been discussed, anyway..

I've noticed, that whoever-the-reason-is really hates when you call somebody. After the talking it's 97% disconnect AAID.

**Comment by berseker** [comment] 2021-05-15 21:01
sorry but after a few days I am facing big connection issue, since two commits ago more or less. sometimes also disconnect\reconnect the bluetooth connection seems to solve. I have sent you @hufman in private the log of une period where I faced issues \ AAI not working

**Comment by DominikS66** [comment] 2021-05-19 19:55
Hope I have some good news today @hufman . New Version 1.4.0 of  MyBMW app has been launched and with this Version the Apps disconnection after around 30 minutes is fixed! I just came to my home from a 2 hour test drive with my BMW F20. No Problems with AAID,  no disconnections, even made some Phone calls without any Problems. Hope this is not a ohne time effect...

**Comment by unlive74** [comment] 2021-05-20 09:51
Unfortunately, the MyBMW 1.4.0 app still connects with "apps" on the second try. Samsung S8, Android 9, BMW X2, ID6L.

**Comment by DominikS66** [comment] 2021-05-20 10:18
@unlive74 I'll also have this problem in about 50% on connection attempts. And it looks like  its "toggling" every time...one time apps work without toggling BT audio, then next connection attempt apps does not work and manual toggle of BT audio is required.

**Comment by unlive74** [comment] 2021-05-20 10:42
@Dominik66 The same.. Well, I tried the MyBMW 1.4.0 app and installed Connected 6.4 app again - it still works flawlessly.

**Comment by dimakaob** [comment] 2021-05-20 10:44
You need to daownload the latest AAiD build. Works perfectly!

**Comment by unlive74** [comment] 2021-05-20 11:09
I I use AAiD 5e0a51c / 16.05.21 - no tunnel is established between the car and MyBMW app and I think this is not a problem with the AAiD app. Perhaps MyBMW doesn't work correctly with ID6L. @DominikS66 what do you think?

**Comment by DominikS66** [comment] 2021-05-20 11:34
@unlive74 I've also ID6L...next step for me is starting some remote debugging to AAID with Android Studio to watch the behavior when apps connection is starting normal and also when it's not starting. I've tried some small hacks already last week to make this connection startup more reliable, but no change.

**Comment by TobifromGermany** [comment] 2021-05-21 11:27
I'll just throw it in here now. With the latest versions of AAID and the MyBMW app, it is currently running very well and stably. In the latest update of the MyBMW app, it was even added whether the app is connected to the mobile device or not. But can it be that AAID no longer automatically establishes a connection but only when the app is opened? I've noticed the last few days. AAID and MyBMW are not put into sleep mode. (Battery optimization)

**Comment by berseker** [comment] 2021-05-26 16:31
I keep having issues in First connection, of i disable/reenable the bluetooth link then It works. I think that main problem Is myBmw app in any case.

myBmw 1.4.1, MIUI 12 android 10, aai nightly (last carinfo branch)

**Comment by unlive74** [comment] 2021-05-26 17:02
@berseker do you have ID6L?

**Comment by berseker** [comment] 2021-05-26 17:19
yes
![image](https://user-images.githubusercontent.com/1159431/119703925-5b696c80-be57-11eb-849e-44c432fa3d76.png)

**Comment by unlive74** [comment] 2021-05-27 05:02
I think this is a problem with the connection between My BMW app and ID6L (connect without "apps") and the best we can do is write to My BMW app's support team to show the scale of the problem. The Connected app also has this problem, only less often ..

**Comment by berseker** [comment] 2021-05-27 05:12
I highlighted a possibile problem via the app bug tracking functionality, highlighting my idu data

I Will update here if i get a reply

hmi.type: BMW ID6L
hmi.version: EntryEvo_ID5_1903_Release ID5_1903-490-1837K Build 47 - Rev:203015 2018-11-14 08:39:42

**Comment by jezikk82** [comment] 2021-05-27 05:58
I can confirm that this issue is related to **EntryEvo**. (lower variant in NBT family).
I experienced this on F48 ID6L and EntryNav from my friend.

Best way is to open MyBMW app, and wait until in phone status bar it shows "connected to car" and after that open AAID and then in 80%+ cases it connects.

**Comment by hufman** [comment] 2021-05-29 00:23
I pushed up a new build that tries triggering Connected to continue connecting, maybe it'll help? It's hard to tell whether it helped in my tests or if I was just in a lucky period and it would've worked anyways! I think this change should help connect in the scenario when the Car Is Connected popup is showing but the Apps connection doesn't start.

**Comment by unlive74** [comment] 2021-05-29 02:21
I don't understand.  For this to work, you need to install both MyBMW and Connected apps?

**Comment by hufman** [comment] 2021-05-29 02:33
No, I'm sorry, I was referring to then collectively. Recent Connected and the MyBMW app use the same Bluetooth connection process, so this change will help either app.

**Comment by unlive74** [comment] 2021-05-29 15:12
> I pushed up a new build that tries triggering Connected to continue connecting...

@hufman MyBMW updated to 1.4.2 today and I installed the latest aaid. I will be testing some more, but it seems the problem has been resolved.
By the way, "Car Info" -> "Chassis" doesn't show anything, just an empty space - although vehicle.type: F39

**Comment by hufman** [comment] 2021-05-29 16:46
Ah very good, you have a new car that the ChassisCodes didn't know about! I [added some more codes](https://github.com/hufman/AndroidAutoIdrive/commit/72908978dd02ab92159b61b6d9fd4c0438121cbb) and that should fix that up for you.

**Comment by DominikS66** [comment] 2021-06-02 14:08
> I confirm that also in my case after this commit my problems of connection seems gone. I am using since a month MyBMW only (mainly for debugging of the connection with your app :D) well done
Full ACK. Connection problems on iDrive startup seem to eliminated. IMHO current state of AAiD is stable now.

**Comment by hufman** [comment] 2021-06-02 14:11
I'm glad to hear! I'll mark this as resolved then, thank you so much!

**Closed by hufman** 2021-06-02 14:11 UTC
