### ISSUE TITLE
MyBMW app still not compatible with vehicles that require wired apps connection?

### ISSUE THREAD

**Issue by samusishere** [hufman/AndroidAutoIdrive#293] opened 2021-05-28 12:30 UTC
Hello everyone, 

As we all are well aware by now, support for the legacy Connected app will be discontinued soon. While I've noticed that BMW has been making improvements to the new MyBMW application set to replace it, I've also noticed that there is still no wired BMW apps support that has been implemented into the new version. Is this an indicator that BMW is completely dropping support for vehicles that will only have access to the wired variant apps connection? I find this quite unnerving as I specifically optioned this feature into my vehicle and for BMW to completely drop support simply because they do not wish to add the additional code from the previous connected app into MyBMW to continue support is a bit unnerving. If this is the case however, does anyone know of a possible solution besides completely retrofitting a new IDrive headunit?

**Comment by hufman** [comment] 2021-05-28 14:53
The easiest solution is to install BMW Connected 6.4 and disable auto updates for it. It doesn't even need to be signed in for the apps connection to work. There are download links in #238 for convenience.

**Comment by samusishere** [comment] 2021-05-28 17:34
Okay perfect, thank you!

**Comment by LACNR** [comment] 2021-05-28 17:45
Eventually with time they will add support, but we need people to point out this on the PlayStore comments section of the app so they get aware of it.

**Comment by hufman** [comment] 2021-06-03 20:11
I believe this is resolved by the current in-app warning saying that USB connections require BMW Connected. If the MyBMW app gains support for USB, it will automatically start working with the app, and the warning can be removed.

**Closed by hufman** 2021-06-03 20:11 UTC

**Comment by masteralarm** [comment] 2021-06-07 12:45
Just a heads up: in the latest version of the MyBMW app it seems more likely that they might add proper USB support in the future:
For the first time, after connecting via USB, I get the Android dialog of which app to start (Connected or MyBMW), which it did not do before with the MyBMW app.
Unfortunately, that's where it ends. No apps are loaded to the car. I am not sure if it is just AndroidAutoiDrive that needs to be modified.

**Comment by hufman** [comment] 2021-06-18 01:08
I encountered this randomly over the weekend, and was able to reproduce it today: Mini 1.4.3 was able to reliably connect over USB on both my Pixel2 and Galaxy S9. The Pixel2 required switching to File Transfer mode as per usual, and the Galaxy S9 didn't immediately start the connection because the Mini app had signed out again, but signing back in (even while staying plugged in) initiated the connection.
After the connection is established, the regular app connection should notice (the Notification Listener subscribes to the official car connection announcement if it's running, the Bluetooth connection listener will start probing, or opening the app will start probing) and then the apps connected in all of my tests.
If there are other confirmations, I'll want to update the wording in the app.
