### ISSUE TITLE
App no longer connceting to car

### ISSUE THREAD

**Issue by ronniebadmf** [hufman/AndroidAutoIdrive#197] opened 2021-01-31 19:09 UTC
![Screenshot_20210131-200232](https://user-images.githubusercontent.com/76211532/106394923-a6bac380-63ff-11eb-9e38-f1686919bd83.png)

App stopped connecting to BMW idrive 6. Several  restarts and reconnections did not solve the problem. Under car phone settings the app selection switches on and off regularly, which shows that it is trying to connect and for whatever reason it fails.

**Comment by hufman** [comment] 2021-02-01 06:22
Good evening, and thanks for the question!

The Apps checkmark in your car is a direct representation of the status of the Apps connection from the car. When BMW Connected establishes the tunnel to the car (even before running any apps over it) this checkmark lights up. Similarly, if this tunnel is shut down for some reason, this checkmark will uncheck.

As such, it is directly controlled by the BMW Connected app. It runs a watchdog process that pings the car every few seconds or so, and will close the connection if this watchdog thinks the connection is stuck. So, we have to figure out why the BMW Connected app is closing the connection in your case.

In your connection debugging, have you tried force-killing the BMW Connected app entirely, not just restarting the connection? I've also experienced a few false starts like you describe when my phone hasn't restarted in a few weeks, I suspect memory pressure causing troubles.
I also removed the other brand from my phone, because I've seen occasional evidence of both BMW and Mini Connected trying to run the tunnel and conflicting, but your screenshot shows that you already don't have Mini Connected installed.

I hope this helps! Since you haven't changed app versions, and BMW Connected hasn't upgraded much recently, it should be a temporary issue that can be figured out.

**Comment by Sven31415** [comment] 2021-02-01 14:40
Hello!
I've actually got the same issue. Also iDrive 6. When the check box is turning on and of over and over again I can fix it by opening the AndroidAuto IDrive App. After that the connection is stable and everything runs fine. So I think the problem is that the AndroidAuto IDrive App has some issues with running in background?
In December I had the same issue, that connection didn't seem to work at all, so I updated to a newer version, but a describe I've still got a similar issue

**Comment by donsaimon** [comment] 2021-02-06 15:00
Same problem here. Connection is very unstable in the last month...

**Comment by Sven31415** [comment] 2021-02-06 15:08
Yes but it must have to do something with background processes, because when I open the App everything works fine immediately

**Comment by donsaimon** [comment] 2021-02-06 15:11
You mean that if you open tha app AndroidAutoIdrive everything is OK?
If yes, I will do a routine to open AndroidAutoIdrive automatically as soon as my phone connects to the car

**Comment by Sven31415** [comment] 2021-02-06 15:23
Exactly!
I think this "bug" could also be fixed internally, but until it is I consider this as a great workaround.

**Comment by donsaimon** [comment] 2021-02-06 15:27
Ok I will try. I have not used AndroidAutoIdrive since December as it connected only once every 4 or 5 times... If this workaround will work, I can use  this fantastic app again!

**Comment by hufman** [comment] 2021-02-06 16:52
I sincerely apologize for any instability! I really try to keep the latest build stable during development, but some things might slip through. I know I fixed some bugs on [Jan 14th](https://github.com/hufman/AndroidAutoIdrive/commit/3dabfde8cd1772ea28530a0837552a935618a44e) regarding initial module startup (which might have been causing random problems for a few months) and on [Jan 23rd](https://github.com/hufman/AndroidAutoIdrive/commit/1b2ceb9709d427b04cba20c83b2f8e3356900481) about continuing to start up after discovering the car's language (which definitely did break automatic connections until opening the phone app).

I do see that a new BMW Connected 6.4.1 came out in [November in the USA](https://apkpure.com/bmw-connected/de.bmw.connected.na/versions), and a new 6.5.0 version came out in [January for Europe](https://apkpure.com/bmw-connected/de.bmw.connected/versions), I hope that's just coincidental! If you are able to peek in `adb logcat` to find any suspicious messages from the BMW Connected or AndroidAutoIdrive apps, those would be useful clues! I think the behavior of the Apps checkmark appearing and disappearing indicates a problem with the BMW Connected tunnel, so it might be a valuable test to downgrade the Connected app version and see if it helps (I'm running a modified version of Mini Connected 6.3.0 with [extra debug logging](https://hufman.github.io/BMWConnectedAnalysis/analysis-approach/)).

The initial screenshot shows the old Phone UI, please try upgrading to the latest build to see if it helps. The new UI, merged [Dec 27](https://github.com/hufman/AndroidAutoIdrive/pull/167), brings the connection details forward to the main screen, including any hints needed to unblock the next stage of the connection.

**Comment by Sven31415** [comment] 2021-02-06 17:11
No need to apologize at all, you're doing such a good job!
I'm always using the latest version (max 1 week delay) and it got better again, but not as it was once. Maybe every 10th connection has those difficulties.

**Comment by donsaimon** [comment] 2021-02-06 21:28
Thanks a lot for your job hufman! How can I upgrade to last version your app? I am currently using 1.2.2 that I thought was the last one...

**Comment by hufman** [comment] 2021-02-06 23:51
Indeed, 1.2.2 is the most recent [release](https://github.com/hufman/AndroidAutoIdrive/releases). Additionally, every successful build is also posted soon after the code is pushed, with links to the [sentry](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/androidautoidrive-latest-master-nomap-sentry-release.apk) and [nonalytics](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/androidautoidrive-latest-master-nomap-nonalytics-release.apk) builds hidden in the main Readme page.

**Comment by hufman** [comment] 2021-05-19 20:35
Good afternoon! I pushed up a few fixes for connection instability over the last few months, and I'm checking to see if you are still experiencing this problem in the most recent versions of the app?

**Comment by donsaimon** [comment] 2021-05-19 20:50
Dear Walter, yes unfortunately I have yet connection problems even with the last updates.
I tried last week after some months, but connection problems are still there for me unfortunately...
Moreover I have no more the line "Audio player"... It is now "Sotify"... Very strange behaviour...

Thanks a lot

Best Regards,

Simone

Da: ***@***.***
Inviato: 19 Maggio 2021 22:36
A: ***@***.***
Rispondi a: ***@***.***
Cc: ***@***.***; ***@***.***
Oggetto: Re: [hufman/AndroidAutoIdrive] App no longer connceting to car (#197)


Good afternoon! I pushed up a few fixes for connection instability over the last few months, and I'm checking to see if you are still experiencing this problem in the most recent versions of the app?

**Comment by hufman** [comment] 2021-05-29 00:25
I pushed up a new build that tries triggering Connected to continue connecting, maybe it'll help? It's hard to tell whether it helped in my tests or if I was just in a lucky period and it would've worked anyways! I think this change should help connect in the scenario when the Car Is Connected popup is showing but the Apps connection doesn't start.

@donsaimon This Spotify icon is the new interface that allows for global coverart, the Audioplayer is built only for ID4 and didn't provide the new coverart feature or the more native interface.

**Comment by donsaimon** [comment] 2021-05-29 20:32
Thanks a lot for your effort Walter. I tried last version today, but I find more reliable (about connection) the previous version.
About the voice "Audio player" that I had on the display menu, now substituted by the voice "Spotify"... My car has Id5 version... nevertheless I had "Audio player" voice...
One question: what does the advanced setting "show always as Spotify in Idrive5+" do?
I see no difference if I enable or disable that voice...
Thanks a lot again
Ciao
Simone
Da: ***@***.***
Inviato: 29 Maggio 2021 02:25
A: ***@***.***
Rispondi a: ***@***.***
Cc: ***@***.***; ***@***.***
Oggetto: Re: [hufman/AndroidAutoIdrive] App no longer connceting to car (#197)


I pushed up a new build that tries triggering Connected to continue connecting, maybe it'll help? It's hard to tell whether it helped in my tests or if I was just in a lucky period and it would've worked anyways! I think this change should help connect in the scenario when the Car Is Connected popup is showing but the Apps connection doesn't start.

@donsaimon<https://github.com/donsaimon> This Spotify icon is the new interface that allows for global coverart, the Audioplayer is built only for ID4 and didn't provide the new coverart feature or the more native interface.

**Comment by hufman** [comment] 2021-05-30 00:55
The app will run as Audioplayer by default. The most recent release only supports Audioplayer mode. After upgrading to a recent build, it will automatically run in Spotify mode if a new enough Spotify is detected.
That Force Spotify Mode checkbox allows it to run as Spotify even without new Spotify installed. If you have old Spotify installed, then both the official Spotify app and this app's Spotify icon will show up. If you don't have any Spotify installed, then the car will still have a Spotify icon installed from this app. So, to reduce confusion, it will only run as Spotify in the right condition by default.

**Comment by donsaimon** [comment] 2021-05-30 10:28
Thanks for your answer Walter.
I tried to install an old version of Spotify. I have now 2 Spotify icons. One from the car and the other one from AAI. BUT NO MORE "AUDIOPLAYER" voice...

Da: ***@***.***
Inviato: 30 Maggio 2021 02:55
A: ***@***.***
Rispondi a: ***@***.***
Cc: ***@***.***; ***@***.***
Oggetto: Re: [hufman/AndroidAutoIdrive] App no longer connceting to car (#197)


The app will run as Audioplayer by default. The most recent release only supports Audioplayer mode. After upgrading to a recent build, it will automatically run in Spotify mode if a new enough Spotify is detected.
That Force Spotify Mode checkbox allows it to run as Spotify even without new Spotify installed. If you have old Spotify installed, then both the official Spotify app and this app's Spotify icon will show up. If you don't have any Spotify installed, then the car will still have a Spotify icon installed from this app. So, to reduce confusion, it will only run as Spotify in the right condition by default.

**Comment by hufman** [comment] 2021-05-30 14:58
Indeed, that is the confusing icon situation that I hope to avoid. If you want it to run as Audioplayer mode now, you'd also need to uncheck that checkbox.
May I ask why you want it to run as Audioplayer? I think Spotify mode includes better functionality.

**Comment by donsaimon** [comment] 2021-05-30 15:11
I would prefer to have the 'audioplayer' voice as Spotify voice only is confusing... If I unceck the voice "show always as spotify in ID5+" the audioplayer voice does not appear. and it does not appear even if I check the box...

Da: ***@***.***
Inviato: 30 Maggio 2021 16:58
A: ***@***.***
Rispondi a: ***@***.***
Cc: ***@***.***; ***@***.***
Oggetto: Re: [hufman/AndroidAutoIdrive] App no longer connceting to car (#197)


Indeed, that is the confusing icon situation that I hope to avoid. If you want it to run as Audioplayer mode now, you'd also need to uncheck that checkbox.
May I ask why you want it to run as Audioplayer? I think Spotify mode includes better functionality.

**Comment by hufman** [comment] 2021-05-30 15:40
Alright, to run as Audioplayer mode, just keep the old Spotify installed (or uninstall entirely) and then uncheck the advanced option.

Please check out the discussion in #251, where I'm planning to add an option to run as Spotify mode, to retain the global coverart functionality, but use the old Audioplayer main screen for the compact layout.

**Comment by donsaimon** [comment] 2021-05-30 20:28
What do you mean with "old Spotify version" which version should I install?
I often have a bug: no more possible randomly to navigate (browse) between Spotify songs of my playlist: the "now playing" button is greyed. I have read that it is a quite common issue, but I have not understood if there is a fix or something I can do to avoid it.
Thanks a lot
Best regards
Simone

Da: ***@***.***
Inviato: 30 Maggio 2021 17:40
A: ***@***.***
Rispondi a: ***@***.***
Cc: ***@***.***; ***@***.***
Oggetto: Re: [hufman/AndroidAutoIdrive] App no longer connceting to car (#197)


Alright, to run as Audioplayer mode, just keep the old Spotify installed (or uninstall entirely) and then uncheck the advanced option.

Please check out the discussion in #251<https://github.com/hufman/AndroidAutoIdrive/issues/251>, where I'm planning to add an option to run as Spotify mode, to retain the global coverart functionality, but use the old Audioplayer main screen for the compact layout.

**Comment by donsaimon** [comment] 2021-06-02 20:15
Dear Walter, sorry for disturbing you.
I have an issue with WhatsApp song browsing. Often the button "now playing" is disabled (greyed) and there is no way to enable again. When this issue occurs, I have noticed that in your app the voice "possibility to navigate in Spotify library" is unchecked and it is not possible to check the box again (see attached image).
I read something related to this issue in the past, but I don't know if there is a fix, or something that I can do to avoid it or something that I could do while in the car to resolve the issue. I have tried to uncheck "Bluetooth audio" voice and then check the "app" voice in the car menu to restart your app, but it did not work...
Thank you
Best Regards,
Simone

Da: ***@***.***
Inviato: 30 Maggio 2021 17:40
A: ***@***.***
Rispondi a: ***@***.***
Cc: ***@***.***; ***@***.***
Oggetto: Re: [hufman/AndroidAutoIdrive] App no longer connceting to car (#197)


Alright, to run as Audioplayer mode, just keep the old Spotify installed (or uninstall entirely) and then uncheck the advanced option.

Please check out the discussion in #251<https://github.com/hufman/AndroidAutoIdrive/issues/251>, where I'm planning to add an option to run as Spotify mode, to retain the global coverart functionality, but use the old Audioplayer main screen for the compact layout.

**Comment by hufman** [comment] 2021-06-02 20:25
Please look in discussion #255 for links to download the latest version of Spotify with official IDrive support. With this version is installed, AAI will run by default as Audioplayer. It sounds like you installed this version already, and just need to uncheck the Appear As Spotify button in AAI.

If there is an error connecting to Spotify to browse, there should be an error message there with more details. You may be experiencing #254 (problems browsing Spotify on a second connection attempt), try force closing Spotify and connecting again. If you are in this state, Spotify doesn't respond properly to the connection attempt, and will time out after some 30 seconds or so, and the error field in the Music tab will stay blank until this time out happens.

**Comment by donsaimon** [comment] 2021-06-02 20:35
Thanks for you answer Walter.
For the 1st point, yes, I tried to install the old last Spotify version officially compatible with iDrive, and I had autoplayer voice again, but I installed the most recent Spotify version again (no more audioplayer voice) because in this case your app provides a better user interface with the possibility to skip forward the song, so I definitely will keep latest Spotify version.

With respect to the Spotify browsing issue, in my case it seems to be randomic and not linked to the number of previous connections...
If I have understood well, the solution is to kill Spotify via phone. It is very uncomfortable when I am driving..
Do you think you will be able to fix this problem in the next versions of your app? Did you experienced this issue? Does it happen to everyone or it depends from e.g. BMW app version or other?

Da: ***@***.***
Inviato: 2 Giugno 2021 22:25
A: ***@***.***
Rispondi a: ***@***.***
Cc: ***@***.***; ***@***.***
Oggetto: Re: [hufman/AndroidAutoIdrive] App no longer connceting to car (#197)


Please look in discussion #255<https://github.com/hufman/AndroidAutoIdrive/discussions/255> for links to download the latest version of Spotify with official IDrive support. With this version is installed, AAI will run by default as Audioplayer. It sounds like you installed this version already, and just need to uncheck the Appear As Spotify button in AAI.

If there is an error connecting to Spotify to browse, there should be an error message there with more details. You may be experiencing #254<https://github.com/hufman/AndroidAutoIdrive/issues/254> (problems browsing Spotify on a second connection attempt), try force closing Spotify and connecting again. If you are in this state, Spotify doesn't respond properly to the connection attempt, and will time out after some 30 seconds or so, and the error field in the Music tab will stay blank until this time out happens.

**Comment by hufman** [comment] 2021-06-02 20:48
I only experience the issue occasionally, maybe once a month or so. It only impacts Spotify, not any of the other music apps I use.
I definitely intend to try to resolve it before the next release. Please watch that #254 issue for updates.

**Comment by donsaimon** [comment] 2021-06-02 20:57
Yes me too have experienced only a few times, but when it happens it is quite annoying.
Thanks a lot for your effort trying to solve this issue, I'll follow #254 hoping for positive updates. Do you think you will be able to solve it in the next days/weeks or it will take more time (months)?
Anyway I noticed that connection failures have become very very rare with latest version of AAI: very good, thank you!

Da: ***@***.***
Inviato: 2 Giugno 2021 22:48
A: ***@***.***
Rispondi a: ***@***.***
Cc: ***@***.***; ***@***.***
Oggetto: Re: [hufman/AndroidAutoIdrive] App no longer connceting to car (#197)


I only experience the issue occasionally, maybe once a month or so. It only impacts Spotify, not any of the other music apps I use.
I definitely intend to try to resolve it before the next release. Please watch that #254<https://github.com/hufman/AndroidAutoIdrive/issues/254> issue for updates.

**Comment by donsaimon** [comment] 2021-06-04 06:53
Dear Walter,
I have an issue with the music app "Energy Radio" that I use via AAI app. If I select one of the channels transmitted by Energy Radio (e.g. Energy Rock) and then I power off the car and I power on the car after some hour, Energy Radio is off, and I have to select again a channel to listen at music... (by pressing the magnifying glass symbol on the left bar menu).
Do you have some suggestion?
Thank you.
Best Regards,
Simone

Da: ***@***.***
Inviato: 2 Giugno 2021 22:48
A: ***@***.***
Rispondi a: ***@***.***
Cc: ***@***.***; ***@***.***
Oggetto: Re: [hufman/AndroidAutoIdrive] App no longer connceting to car (#197)


I only experience the issue occasionally, maybe once a month or so. It only impacts Spotify, not any of the other music apps I use.
I definitely intend to try to resolve it before the next release. Please watch that #254<https://github.com/hufman/AndroidAutoIdrive/issues/254> issue for updates.

**Comment by hufman** [comment] 2021-06-04 19:33
If the Browse functionality is working, then the car app is successfully connected to the music app, and the music app itself isn't behaving nicely. I experience this with the RMC Radio Monte Carlo app, and there isn't much the car app can do. Even when trying to control RMC with Android Auto, it jumps right to the Browse functionality and doesn't offer an option for resuming playback.
Install the Android Auto app on your phone and try using Energy Radio in it and see what it does. The best thing to do would be to write to Energy Radio and suggest they support resuming playback when Android Auto connects: It's inconvenient (and relatively unsafe) to fiddle with the Android Auto interface just to get music playing again, so resuming the previous playback would make sense.

**Comment by donsaimon** [comment] 2021-06-04 19:51
Understood Walter thank you. So it is an Energy Radio app issue.
P. S. Radio Monte Carlo is an Italian radio. Glad you appreciate it.

Da: ***@***.***
Inviato: 4 Giugno 2021 21:34
A: ***@***.***
Rispondi a: ***@***.***
Cc: ***@***.***; ***@***.***
Oggetto: Re: [hufman/AndroidAutoIdrive] App no longer connceting to car (#197)


If the Browse functionality is working, then the car app is successfully connected to the music app, and the music app itself isn't behaving nicely. I experience this with the RMC Radio Monte Carlo app, and there isn't much the car app can do. Even when trying to control RMC with Android Auto, it jumps right to the Browse functionality and doesn't offer an option for resuming playback.
Install the Android Auto app on your phone and try using Energy Radio in it and see what it does. The best thing to do would be to write to Energy Radio and suggest they support resuming playback when Android Auto connects: It's inconvenient (and relatively unsafe) to fiddle with the Android Auto interface just to get music playing again, so resuming the previous playback would make sense.

**Comment by berseker** [comment] 2021-06-05 08:06
I noticed you are talking about "energy radio" app, below a screenshot showing some strange behaviour of this app (I do not know if the cause it's the app itself, or AAI not tracking properly the tags given by this app)


![image](https://user-images.githubusercontent.com/1159431/120884824-be8c9900-c5e5-11eb-8762-2fe0c73b9019.png)

**Comment by hufman** [comment] 2021-06-05 08:13
AAI logs the tags that it receives from the app, look in your `adb logcat` for the keyword `MediaMetadata`. The PhoneUI player uses the same code, so you can leave it connected to your computer to watch the logs while trying different songs or apps.

**Comment by berseker** [comment] 2021-06-05 09:22
https://pastebin.com/8iCrDi8G here is the log of the minutes I was testing the app

**Comment by hufman** [comment] 2021-06-05 18:30
The log didn't catch anything, because it only logs if the MediaMetadata's MEDIA_ID has changed. This app doesn't provide very much metadata at all:
```Parsing MediaMetadata Bundle{ android.media.metadata.DISPLAY_SUBTITLE -> Tout l'univers - Gjon's Tears, android.media.metadata.COMPILATION -> Energy Basel, android.media.metadata.ALBUM_ART_URI -> https://cdn.energy.ch/energych-broadcast/covers/songs/500x500-c-q40/32719_1621237106.jpg, android.media.metadata.DISPLAY_TITLE -> Energy Basel, android.media.metadata.ALBUM -> Tout l'univers }```
For this song, for example, `Tout l'univers` is the song's title and `Gjon's Tears` is the artist. There isn't a good generic way to extract the artist from this (I definitely don't want to start special-casing parsing logic for each app), but the full DISPLAY_SUBTITLE might be able to be displayed.
I'll try to come up with a generic way to improve this, but the Energy app really should be emitting proper data.

**Comment by berseker** [comment] 2021-06-05 20:47
I would leave a comment on the app page on Google Play if I would be able to express properly which is the problem of their app :D

**Comment by berseker** [comment] 2021-06-06 09:36
@hufman Much Better :)
![IMG_20210606_113408](https://user-images.githubusercontent.com/1159431/120919716-54462800-c6bb-11eb-9b48-0b404e39b11a.jpg)

**Comment by donsaimon** [comment] 2021-06-06 12:54
How may I have this layout???

**Comment by hufman** [comment] 2021-06-06 14:53
Which layout do you refer to? The screenshots show the NRJ Energy Radio app, the AAI Spotify mode playback screen, and the ID6L home screen music tile.

**Comment by donsaimon** [comment] 2021-06-06 14:54
Yes, exactly

Da: ***@***.***
Inviato: 6 Giugno 2021 16:53
A: ***@***.***
Rispondi a: ***@***.***
Cc: ***@***.***; ***@***.***
Oggetto: Re: [hufman/AndroidAutoIdrive] App no longer connceting to car (#197)


Which layout do you refer to? The screenshots show the NRJ Energy Radio app, the AAI Spotify mode playback screen, and the ID6L home screen music tile.

**Comment by hufman** [comment] 2021-06-24 05:48
This particular type of instability seems resolved, so I'll close it out.

**Closed** 2021-06-24 05:52 UTC

**Comment by donsaimon** [comment] 2021-09-27 13:30
Dear Walter, it would be useful to mark as read all the messages at once, without having to open every single message and mark it as read. Do you think it is possible?
Thank you
Best Regards,
Simone
