### ISSUE TITLE
Song autoplay after back to car

### ISSUE THREAD

**Issue by Kamil2398** [hufman/AndroidAutoIdrive#286] opened 2021-05-24 16:16 UTC
Has anyone noticed the problem with the autostart of a song from Spotify? Everything connects correctly, it reads the cover, but there is no sound  I have to click the media button on the iDrive in the main menu, then the music starts playing. This situation occurs when I leave the car as AAID Spotify media. Tomorrow or the day after tomorrow I will try to record a film of this event. (Spotify connection is always killed by me manual so the number #254  is not a problem)

**Comment by bogdan-calapod** [comment] 2021-05-25 15:44
I've also noticed this a couple of times, but couldn't reproduce it.

**Comment by Kamil2398** [comment] 2021-05-25 16:46
Today I failed to record, I did not take a second phone, but I looked at what it looks like on the phone my bmw connects then AAI opens and calls Spotify connection, but here the implus that would say play is missing. It does not show the currently playing song in the notifications, it is just a Spotify connection notification, when I press the media button on the idrive, a notification with the currently playing song pops up and the music starts playing.

**Comment by Kamil2398** [comment] 2021-05-25 18:55
Recorded successfully, it is 80% of the time

**Comment by donsaimon** [comment] 2021-06-08 07:15
Some solution? This happens quite frequently... Almost 50% of times audio is mute and I have to press "media" button near the iDrive wheel...

**Comment by hufman** [comment] 2021-06-13 04:46
Has anyone experienced this in any app besides Spotify? I captured logs from one time I experienced this, and it looks like the app is creating two connections quickly to the music app, which Spotify is not usually happy with, and so it's ignoring the auto-resume command. This might be helped if I can figure out #254.

**Comment by donsaimon** [comment] 2021-06-13 07:57
I experienced this In Spotify only. And it happens quite often.

**Comment by donsaimon** [comment] 2021-06-13 10:17
Dear Walter, how may I install the fix for double connections of Spotify? See image attached

________________________________
  Messaggio originale
________________________________
Mostra dettagli
Da: ***@***.******@***.***>
Inviato: 13 Giugno 2021 06:46
A: ***@***.******@***.***>
Rispondi a: ***@***.******@***.***>
Cc: ***@***.******@***.***>; ***@***.******@***.***>
Oggetto: Re: [hufman/AndroidAutoIdrive] Song autoplay after back to car (#286)


Has anyone experienced this in any app besides Spotify? I captured logs from one time I experienced this, and it looks like the app is creating two connections quickly to the music app, which Spotify is not usually happy with, and so it's ignoring the auto-resume command. This might be helped if I can figure out #254<https://github.com/hufman/AndroidAutoIdrive/issues/254>.

**Comment by hufman** [comment] 2021-06-13 16:46
The image didn't come through the email, but if you have two Spotify apps showing, it's probably from enabling the Advanced Option to Force Spotify Mode while also running the older Spotify version that still supports iDrive. Connected might also be remembering when this older Spotify was installed and show a placeholder icon for it, which should be fixed by clearing it's storage or uninstalling and reinstalling Connected entirely. The new MyBMW doesn't support those 3rd-party apps anyways, so upgrading to MyBMW will clear that extra icon too (at the cost of losing the Calendar app and ID4 support).

**Comment by donsaimon** [comment] 2021-06-13 19:00
Walter I only have 1 Spotify icon, and it is AAI icon. 
In my previous message, I was referring to your commit that (your words) "Should reduce double-connection issues when reconnecting to car
observed in #286 and maybe also #254" 
I was asking if there is some fixing code and how to install it. 
Thank you.

**Comment by hufman** [comment] 2021-06-13 19:02
Oh that's just pushed to the normal [automatic build](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/androidautoidrive-latest-master-nomap-sentry-release.apk). I don't know if it fixed anything though, a later attempt triggered the same problem.

**Comment by donsaimon** [comment] 2021-06-13 19:04
So I have to download apk again? I downloaded more or less 15 days ago...

**Comment by hufman** [comment] 2021-06-13 19:35
Yes, there are currently no automatic updates so if you want to try the latest code, you'll have to download again.

**Closed** 2021-06-19 04:51 UTC

**Comment by hufman** [comment] 2021-06-19 06:09
I think I pushed a fix to this, please verify!

**Comment by donsaimon** [comment] 2021-06-19 15:30
Seems OK, but only supports Spotify app.... Not other music apps, nevertheless I have enabled them in AAI app.....

**Comment by hufman** [comment] 2021-06-19 17:44
The change should be generic, can you explain what you mean by "only supports Spotify app"? What other music apps are you trying, and what are you seeing instead of the expected behavior?

**Comment by donsaimon** [comment] 2021-06-19 18:31
As in the previous version, I use Spotify, simpler audio and Energy Radio.
With the previous versions, I could select, by means of iDrive wheel, among one of my three apps. Now, with this last version, I see only Spotify app on the screen of my car, I do not see Simple Radio and Energy anymore...

**Comment by donsaimon** [comment] 2021-06-19 20:52
EDIT: uninstalled and installed AAI app again and every app is OK now (visible on my car display)

**Comment by donsaimon** [comment] 2021-06-20 22:01
Even with the latest version (39118e1) downloaded and installed this evening, same problems: Simple Radio app is mute, Spotify music 1 second ok, 3 seconds mute, system very very slow...
The last version that works for me is 2fdabe5...
Help pls!

**Comment by hufman** [comment] 2021-06-20 23:17
Do you have a Huawei phone? Did you enable background execution for each music app? Do they work better if the Spotify or Simple Radio Android app is open? I haven't heard this problem before, but someone once told me that MIUI works better with background execution enabled for the music apps.

**Comment by hufman** [comment] 2021-06-21 00:46
I tweaked some of the autoresume functionality, maybe it'll help?

**Comment by donsaimon** [comment] 2021-06-21 06:48
I have a Samsung phone (S20 FE 5G).
I do not experience crashes, but apps works very bad... The first time I installed one of the new versions only Spotify was displayed in terms of music apps that I could choose and Spotify ran very well. Then I uninstalled and installed again AAI and also other music apps were visible, but they now work very bad. When I use 16th June release everything is fine (except for issue #254 that is still present), but as soon as I install one of the following versions (the one that solves #254 and the following versions) the problems start...

**Comment by hufman** [comment] 2021-06-21 16:53
Can you narrow down what you mean by "work very bad"? This is a subjective quality that is very hard for me to reproduce.
Can you try to identify what has changed [since that release](https://github.com/hufman/AndroidAutoIdrive/compare/1.3rc2...master) that would cause problems? At each version in that list, the green checkmark links to the automatic build, which includes an APK compiled at each version. Perhaps you are experiencing a problem with 0409a35, which I adjusted in version 1fc6d11 yesterday, and am interested to hear if it helped.
Can you see any problems in `adb logcat`? Can you build the app yourself and look in the Android Studio Profiler output to find any performance problems?
Without more details, I can only make guesses, which seems to not be very successful so far.

**Comment by donsaimon** [comment] 2021-06-21 20:54
With "works very bad" I mean that Spotify reproduces 1 second of music, then stops for 3 seconds,  then 3 seconds of music and stops for 2-3 seconds, and so on. When I try to change music app on my car using the iDrive control wheel, the systems responds late (3 or 4 seconds if lag).
Today I installed

**Comment by hufman** [comment] 2021-06-22 00:40
Glad to hear! I had tested 0409a35 against Spotify successfully but hadn't tested other apps, and I discovered that Radio FM was being sent infinitely-many Play commands but never switching the status to Play to break the loop, so I added 1fc6d11 to stop after a few attempts.
